name: Delete All Workflow Runs

on:
  workflow_dispatch:

jobs:
  delete-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete all workflow runs
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            
            console.log(`Deleting all workflow runs for ${owner}/${repo}`);
            
            for await (const response of github.paginate.iterator(
              github.rest.actions.listWorkflowRunsForRepo,
              {
                owner,
                repo,
                status: 'completed'
              }
            )) {
              const runs = response.data;
              for (const run of runs) {
                console.log(`Deleting workflow run ${run.id}`);
                await github.rest.actions.deleteWorkflowRun({
                  owner,
                  repo,
                  run_id: run.id
                });
              }
            }
