name: Build and Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    name: Build RootHide Bootstrap
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"
          git remote add upstream https://github.com/RootHide/Bootstrap
          git fetch upstream
          git fetch --all --prune
          git pull --rebase --strategy-option=theirs upstream main
          
      - name: Install Homebrew
        run: bash -c "$(curl -fsSL 'https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh')"

      - name: Install Theos
        run: bash -c "$(curl -fsSL 'https://raw.githubusercontent.com/roothide/theos/master/bin/install-theos')"

      - name: Install make
        run: brew install make

      - name: Setup Theos environment
        run: echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: set version
        id: get_version
        run: |
          LATEST_COMMIT_MSG=$(git log -1 --pretty=%B)
          VERSION_REGEX="Version ([0-9]+\.[0-9]+\.[0-9]+)"
          if [[ $LATEST_COMMIT_MSG =~ $VERSION_REGEX ]]; then
            echo "VERSION=${BASH_REMATCH[1]}" >> $GITHUB_ENV
            echo "::set-output name=version::${BASH_REMATCH[1]}"
          else
            echo "No version found in commit message."
            exit 1

      - name: Make bootstrap package
        run: gmake -j$(sysctl -n hw.ncpu) package

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Bootstrap.tipa
          path: ./packages/Bootstrap.tipa

      - name: Delete old release
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          delete_release: true
          tag_name: v${{ steps.get_version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Get bootstrap artifact
        uses: actions/download-artifact@v3
        with:
          name: Bootstrap.tipa

      - name: Create new release
        uses: ncipollo/release-action@v1
        with:
          name: Bootstrap_beta v${{ steps.get_version.outputs.version }} Release
          body: Installation of this beta file is at the user's own risk and responsibility. No person, including the developers and suppliers of this file, shall be held responsible for any consequences resulting from its installation on the user's phone.
          artifacts: "Bootstrap.tipa"
          tag: v${{ steps.get_version.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
