name: Build and Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  check-for-changes:
    runs-on: macos-latest
    outputs:
      changes_detected: ${{ steps.check_changes.outputs.changes_detected }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check for new commits in sync-fork
        id: check_changes
        run: |
         git remote add upstream https://
          github.com/RootHide/Bootstrap
          git fetch upstream main
          CHANGE_COUNT=$(git rev-list HEAD...upstream/main --count)
          if [ "$CHANGE_COUNT" -gt 0 ]; then
            echo "New changes detected"
            echo "changes_detected=true" >> $GITHUB_ENV
          else
            echo "No changes since last build"
            echo "changes_detected=false" >> $GITHUB_ENV

  build:
    name: Build RootHide Bootstrap
    runs-on: macos-latest
    needs: check-for-changes
    if: ${{ needs.check-for-changes.outputs.changes_detected == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"
          git remote add upstream https://github.com/RootHide/Bootstrap
          git fetch upstream
          git fetch --all --prune
          git pull --rebase --strategy-option=theirs upstream main

      - name: Install Homebrew
        run: bash -c "$(curl -fsSL 'https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh')"

      - name: Install Theos
        run: bash -c "$(curl -fsSL 'https://raw.githubusercontent.com/roothide/theos/master/bin/install-theos')"

      - name: Install make
        run: brew install make

      - name: Setup Theos environment
        run: echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Set Version 
        run: echo "VERSION=4.3" >> $GITHUB_ENV

      - name: Make bootstrap package
        run: gmake -j$(sysctl -n hw.ncpu) package

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Bootstrap.tipa
          path: ./packages/Bootstrap.tipa

      - name: Delete old release
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          delete_release: true
          tag_name: v${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Create new release
        uses: ncipollo/release-action@v1
        with:
          name: Bootstrap_beta v${{ env.VERSION }} Release
          body: Installation of this beta file is at the user's own risk and responsibility. No person, including the developers and suppliers of this file, shall be held responsible for any consequences resulting from its installation on the user's phone.
          artifacts: "Bootstrap.tipa"
          tag: v${{ env.VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
